VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CommonChecker"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Message for modders
' It is obvious that Japanese(kanji) is better than English in the point of number of character.
' And, You won't understand the creepy English you were forced to translate.
' How in the world do you expect me to translate "teiji-nai zangyou jikan"?

Option Explicit

Private Time
